server:
  port: 1001
  tomcat:
    threads:
      max: 1
      min-spare: 1



# redis properties
redis:
  host: 52.79.61.39
  port: 6379
  db: 12


# common properties
sample:
  data:
    count: 10_000


spring:
  task:
    execution:
      thread-name-prefix: mins-thread
  data:
    mongodb:
      uri: localhost
      port: 27017
      database: ranking