server:
  port: 1001
  tomcat:
    threads:
      max: 1
      min-spare: 1


# redis properties
redis:
  host: localhost
  port: 6379
  db: 1


# common properties
sample:
  data:
    count: 100


spring:
  task:
    execution:
      thread-name-prefix: mins-thread